version: '3.3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'demoappdb'
      MYSQL_ROOT_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3309:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db: